before_script:
  - echo "before script"
  # let users can modify its own files.
  # git object files are 444 (read-only for everyone.)
  - chmod u+w -R .git/

after_script:
  - echo "after script"

stages:
  - install
  - check_version
  - test_help
  - test_GADA
  - uninstall
  - compile

install:
  stage: install
  script:
    - pip3 install --user ./


check_version:
  stage: check_version
  script:
    - echo "Checking the version of the installed package"
    - python3 -c "import palos; print(palos.version)"

test_SunsetDB:
  stage: test_help
  script:
    - echo "Testing if SunsetDB.py can print help."
    - pwd
    - ./palos/db/SunsetDB.py -h

test_ImportSeq:
  stage: test_help
  script:
    - echo "Testing if ImportIndividualSequence2DB.py can print help."
    - pwd
    - ./db/import/ImportIndividualSequence2DB.py -h

test_RegisterDB:
  stage: test_help
  script:
    - echo "Testing if RegisterAndMoveSplitSequenceFiles.py can print help."
    - pwd
    - ./db/import/RegisterAndMoveSplitSequenceFiles.py -h

test_GADA:
  stage: test_GADA
  script:
    - echo "Compiling GADA and test-run its Python2 module ... "
    - pwd
    - cd GADA && make
    - ./testGADA.py -i input.txt -o output.tsv
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - GADA/output.tsv

uninstall:
  stage: uninstall
  script:
    - pip3 uninstall -y palos

compile:
  stage: compile
  script:
    - echo "Compile other C++ programs and modules ... "
    - pwd
    - pushd io && make && popd
    - pushd mapper && make && popd
    - pushd polymorphism && make && popd
    - pushd reducer && make && popd
