before_script:
  - echo "before script"
  # let users can modify its own files.
  # git object files are 444 (read-only for everyone.)
  - chmod u+w -R .git/

after_script:
  - echo "after script"

stages:
  - install
  - check_version
  - output_help
  - test_run
  - uninstall

# Py2_install:
#   stage: install
#   script:
#     - pip2 install --user ./

Py3_install:
  stage: install
  script:
    - pip3 install --user ./

# Py2_check_version:
#   stage: check_version
#   script:
#     - echo "Checking the version of the installed package"
#     - python2 -c "import palos; print(palos.version)"

Py3_check_version:
  stage: check_version
  script:
    - echo "Checking the version of the installed package"
    - python3 -c "import palos; print(palos.version)"

SunsetDB_h:
  stage: output_help
  script:
    - echo "Testing if SunsetDB.py can print help."
    - pwd
    - ./palos/db/SunsetDB.py -h

ImportSeq_h:
  stage: output_help
  script:
    - echo "Testing if ImportIndividualSequence2DB.py can print help."
    - pwd
    - ./db/import/ImportIndividualSequence2DB.py -h

RegisterDB_h:
  stage: output_help
  script:
    - echo "Testing if RegisterAndMoveSplitSequenceFiles.py can print help."
    - pwd
    - ./db/import/RegisterAndMoveSplitSequenceFiles.py -h

EstimateOutliersIn2DData_h:
  stage: output_help
  script:
    - echo "Testing if EstimateOutliersIn2DData.py can print help."
    - pwd
    - ./statistics/EstimateOutliersIn2DData.py -h

CNV_h:
  stage: output_help
  script:
    - echo "palos/polymorphism/CNV.py self-run ... "
    - pwd
    - python3 ./palos/polymorphism/CNV.py

Py3_Red-Black Tree:
  stage: test_run
  script:
    - echo "Testing RB Dict and RB List ... "
    - pwd
    - python3 ./palos/algorithm/RBTree.py

# Py2_Red-Black Tree:
#   stage: test_run
#   script:
#     - echo "Testing RB Dict and RB List ... "
#     - pwd
#     - python2 ./palos/algorithm/RBTree.py

CNV:
  stage: test_run
  script:
    - echo "Compare the query efficiency between two different databases of identical content... "
    - pwd
    - cd test
    - ./compare_two_sets_of_segments.py  -q HCC1187_10X_0_3_chr1.segments.M10.T5.tsv -d HCC1187_10X_0_3_chr1.segments.M20.T10.tsv


GADA:
  stage: test_run
  script:
    - echo "Compiling GADA and test-run its C++ binary ... "
    - pwd
    - cd GADA && make
    - ./GADA -i input.txt -o output_CPP.tsv
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - GADA/output_CPP.tsv

pyGADA:
  stage: test_run
  script:
    - echo "Compiling GADA and test-run its Python2 module ... "
    - pwd
    - cd GADA && make
    - ./testGADA.py -i input.txt -o output_py.tsv
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - GADA/output_py.tsv

DAG_CountReadsWorkflow:
  stage: test_run
  script:
    - echo "Output a CountReadsWorkflow DAG ... "
    - pwd
    - ./ngs/qc/CountReadsWorkflow.py -i 790-800 -o CountReads.ISQ790-800.yml
      -l condor --pymodulePath `pwd`
      --hostname pdc --dbname pmdb --schema sunset
      -u sunset_r -p yfishLabSunset --commit
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - CountReads.ISQ790-800.yml
  allow_failure: true

DAG_ShortRead2Alignment:
  stage: test_run
  script:
    - echo "Output a ShortRead2Alignment DAG ... "
    - pwd
    - ./ngs/alignment/ShortRead2Alignment.py --ind_seq_id_ls 787-811
      -a 633 -o Alignment_isq_787_811_vs_633.yml -l condor
      --home_path /y/home/huangyu --pymodulePath `pwd`
      --tmpDir /y/scratch/tmp/huangyu/
      --no_of_aln_threads 8
      -z pdc --dbname pmdb --schema sunset
      -u sunset_r -p yfishLabSunset
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - Alignment_isq_787_811_vs_633.yml
  allow_failure: true

DAG_InspectAlignment:
  stage: test_run
  script:
    - echo "Output a InspectAlignmentPipeline DAG ... "
    - pwd
    #InspectAlignmentPipeline needs some compiled binaries
    - make all
    - ./ngs/qc/InspectAlignmentPipeline.py -a 633 -i 2112-2132 -l condor -z pdc
      --dbname pmdb --schema sunset -u sunset_r -p yfishLabSunset
      --home_path /y/home/huangyu --pymodulePath `pwd`
      --tmpDir /y/scratch/tmp/huangyu/
      -o InspectAln_2112_2132.yml
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - InspectAln_2112_2132.yml
  allow_failure: true


DAG_InspectBaseQuality:
  stage: test_run
  script:
    - echo "Output a InspectBaseQualityPipeline DAG ... "
    - pwd
    - ./ngs/qc/InspectBaseQualityPipeline.py -a 633 -i 650-850 -l condor -z pdc
      --dbname pmdb --schema sunset -u sunset_r -p yfishLabSunset
      --home_path /y/home/huangyu --pymodulePath `pwd`
      --tmpDir /y/scratch/tmp/huangyu/
      -o InspectBaseQuality_650_850.yml
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - InspectBaseQuality_650_850.yml
  allow_failure: true


InspectBaseQuality:
  stage: test_run
  script:
    - echo "Run a InspectBaseQuality.py ... "
    - pwd
    - mkdir input
    - ln -s /y/Sunset/db/individual_sequence/660_indID570_codeEC008_sequencer10000_seqType5_tissueID62_filtered0_batch1_version1/38130_660_WGC090564D_combined_R1_1_12.fastq.gz
      ./input
    - ./ngs/qc/InspectBaseQuality.py --drivername postgresql --hostname pdc
      --schema sunset --dbname pmdb
      --db_user sunset_r --db_passwd yfishLabSunset
      -i input/38130_660_WGC090564D_combined_R1_1_12.fastq.gz
      --logFilename input/38130_660_WGC090564D_combined_R1_1_12.log
      --read_sampling_rate 0.005 --quality_score_format Standard
    - rm input/38130_660_WGC090564D_combined_R1_1_12.fastq.gz
    - mv input output
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - output

ReduceMatrixBySumSameKeyColsAndThenDivide:
  stage: test_run
  script:
    - echo "Test ReduceMatrixBySumSameKeyColsAndThenDivide.py"
    - pwd
    - ./reducer/ReduceMatrixBySumSameKeyColsAndThenDivide.py -k 0 -v 7,6
      -o reducer/data/return_per_stock.csv reducer/data/trade_merged.csv.gz
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - reducer/data/return_per_stock.csv

ReduceMatrixByAverageColumnsWithSameKey:
  stage: test_run
  script:
    - echo "Test ReduceMatrixByAverageColumnsWithSameKey.py"
    - pwd
    - ./reducer/ReduceMatrixByAverageColumnsWithSameKey.py -k 3 -v 4
      -o reducer/data/avg_rtn_duration.csv reducer/data/trade_merged.csv.gz
    - ./palos/plot/AbstractPlot.py -i reducer/data/avg_rtn_duration.csv 
      -o reducer/data/duration_vs_median_rtn.png --xColumnHeader duration
      --whichColumnHeader median_rtn
    - ./palos/plot/AbstractPlot.py -i reducer/data/avg_rtn_duration.csv 
      -o reducer/data/duration_vs_mean_rtn.png --xColumnHeader duration
      --whichColumnHeader mean_rtn
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - reducer/data/avg_rtn_duration.csv
    - reducer/data/duration_vs_median_rtn.png
    - reducer/data/duration_vs_mean_rtn.png

AbstractPlot:
  stage: test_run
  script:
    - echo "Test AbstractPlot"
    - pwd
    - ./palos/plot/AbstractPlot.py -i reducer/data/trade_merged.csv.gz 
      -o reducer/data/duration_vs_rtn_unit.png --xColumnHeader duration
      --whichColumnHeader rtn_unit --fitType 1 --legendType 1
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - reducer/data/duration_vs_rtn_unit.png


DrawHistogram:
  stage: test_run
  script:
    - echo "Test DrawHistogram"
    - pwd
    - ./plot/DrawHistogram.py -i reducer/data/trade_merged.csv.gz 
      -o reducer/data/profit_hist.png --whichColumnHeader profit
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - reducer/data/profit_hist.png

Draw2DHistogramOfMatrix:
  stage: test_run
  script:
    - echo "Test Draw2DHistogramOfMatrix"
    - pwd
    - ./plot/Draw2DHistogramOfMatrix.py -i reducer/data/trade_merged.csv.gz 
      -o reducer/data/signal_open_vs_rtn_unit_2D.png --xColumnHeader signal_open
      --whichColumnHeader=rtn_unit
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - reducer/data/signal_open_vs_rtn_unit_2D.png

uninstall:
  stage: uninstall
  script:
    - pip3 uninstall -y palos