before_script:
  - echo "before script"
  # let users can modify its own files.
  # git object files are 444 (read-only for everyone.)
  - chmod u+w -R .git/

after_script:
  - echo "after script"

stages:
  - install
  - check_version
  - output_help
  - test_run
  - uninstall
  - compile

install:
  stage: install
  script:
    - pip3 install --user ./


check_version:
  stage: check_version
  script:
    - echo "Checking the version of the installed package"
    - python3 -c "import palos; print(palos.version)"

SunsetDB_h:
  stage: output_help
  script:
    - echo "Testing if SunsetDB.py can print help."
    - pwd
    - ./palos/db/SunsetDB.py -h

ImportSeq_h:
  stage: output_help
  script:
    - echo "Testing if ImportIndividualSequence2DB.py can print help."
    - pwd
    - ./db/import/ImportIndividualSequence2DB.py -h

RegisterDB_h:
  stage: output_help
  script:
    - echo "Testing if RegisterAndMoveSplitSequenceFiles.py can print help."
    - pwd
    - ./db/import/RegisterAndMoveSplitSequenceFiles.py -h

GADA:
  stage: test_run
  script:
    - echo "Compiling GADA and test-run its Python2 module ... "
    - pwd
    - cd GADA && make
    - ./testGADA.py -i input.txt -o output.tsv
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - GADA/output.tsv

CountReadsWorkflow:
  stage: test_run
  script:
    - echo "Output a CountReadsWorkflow DAG ... "
    - pwd
    - ./ngs/qc/CountReadsWorkflow.py -i 790-800 -o CountReads.ISQ790-800.xml
      -l condor --pymodulePath `pwd`
      --hostname pdc --dbname pmdb --schema sunset
      -u sunset_r -p yfishLabSunset --commit
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - CountReads.ISQ790-800.xml


ShortRead2Alignment:
  stage: test_run
  script:
    - echo "Output a ShortRead2Alignment DAG ... "
    - pwd
    - ./ngs/alignment/ShortRead2Alignment.py --ind_seq_id_ls 787-811
      -a 633 -o Alignment_isq_787_811_vs_633.xml -l condor
      --home_path /y/home/huangyu --pymodulePath `pwd`
      --tmpDir /y/scratch/tmp/huangyu/
      --no_of_aln_threads 8
      -z pdc --dbname pmdb --schema sunset
      -u sunset_r -p yfishLabSunset
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - Alignment_isq_787_811_vs_633.xml

InspectAlignmentPipeline:
  stage: test_run
  script:
    - echo "Output a InspectAlignmentPipeline DAG ... "
    - pwd
    - ./ngs/qc/InspectAlignmentPipeline.py -i 2112-2132 -l condor -z pdc
      --dbname pmdb --schema sunset -u sunset_r -p yfishLabSunset
      --home_path /y/home/huangyu --pymodulePath `pwd`
      --tmpDir /y/scratch/tmp/huangyu/
      -o Inspect_Aln_2112_2132.xml
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - Inspect_Aln_2112_2132.xml

uninstall:
  stage: uninstall
  script:
    - pip3 uninstall -y palos

compile:
  stage: compile
  script:
    - echo "Compile other C++ programs and modules ... "
    - pwd
    - pushd io && make && popd
    - pushd mapper && make && popd
    - pushd polymorphism && make && popd
    - pushd reducer && make && popd
