before_script:
  - echo "before script"
  # let users can modify its own files. git object files are 444 (read-only for everyone.)
  - chmod u+w -R .git/

after_script:
  - echo "after script"

stages:
  - install
  - check_version
  - test_help
  - compile_GADA
  - test_GADA
  - uninstall

install:
  stage: install
  script:
    - pip3 install --user ./


check_version:
  stage: check_version
  script:
    - echo "Checking the version of the installed package"
    - python3 -c "import palos; print(palos.version)"

test_SunsetDB:
  stage: test_help
  script:
    - echo "Testing if SunsetDB.py can be run ... "
    - pwd
    - ./palos/db/SunsetDB.py -h

test_ImportSeq:
  stage: test_help
  script:
    - echo "Testing if ImportIndividualSequence2DB.py can be run ... "
    - pwd
    - ./db/import/ImportIndividualSequence2DB.py -h

compile_GADA:
  stage: compile_GADA
  script:
    - echo "Compiling GADA ... "
    - pwd
    - cd GADA && make

test_GADA:
  stage: test_GADA
  script:
    - echo "Compiling GADA and test-run its Python2 module... "
    - pwd
    - cd GADA && make
    - ./testGADA.py -i input.txt -o output.tsv

uninstall:
  stage: uninstall
  script:
    - pip3 uninstall -y palos