before_script:
  - echo "before script"
  # let users can modify its own files.
  # git object files are 444 (read-only for everyone.)
  - chmod u+w -R .git/

after_script:
  - echo "after script"

stages:
  - install
  - check_version
  - output_help
  - test_run
  - uninstall

install:
  stage: install
  script:
    - pip3 install --user ./


check_version:
  stage: check_version
  script:
    - echo "Checking the version of the installed package"
    - python3 -c "import palos; print(palos.version)"

SunsetDB_h:
  stage: output_help
  script:
    - echo "Testing if SunsetDB.py can print help."
    - pwd
    - ./palos/db/SunsetDB.py -h

ImportSeq_h:
  stage: output_help
  script:
    - echo "Testing if ImportIndividualSequence2DB.py can print help."
    - pwd
    - ./db/import/ImportIndividualSequence2DB.py -h

RegisterDB_h:
  stage: output_help
  script:
    - echo "Testing if RegisterAndMoveSplitSequenceFiles.py can print help."
    - pwd
    - ./db/import/RegisterAndMoveSplitSequenceFiles.py -h

GADA:
  stage: test_run
  script:
    - echo "Compiling GADA and test-run its Python2 module ... "
    - pwd
    - cd GADA && make
    - ./testGADA.py -i input.txt -o output.tsv
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - GADA/output.tsv

DAG_CountReadsWorkflow:
  stage: test_run
  script:
    - echo "Output a CountReadsWorkflow DAG ... "
    - pwd
    - ./ngs/qc/CountReadsWorkflow.py -i 790-800 -o CountReads.ISQ790-800.xml
      -l condor --pymodulePath `pwd`
      --hostname pdc --dbname pmdb --schema sunset
      -u sunset_r -p yfishLabSunset --commit
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - CountReads.ISQ790-800.xml


DAG_ShortRead2Alignment:
  stage: test_run
  script:
    - echo "Output a ShortRead2Alignment DAG ... "
    - pwd
    - ./ngs/alignment/ShortRead2Alignment.py --ind_seq_id_ls 787-811
      -a 633 -o Alignment_isq_787_811_vs_633.xml -l condor
      --home_path /y/home/huangyu --pymodulePath `pwd`
      --tmpDir /y/scratch/tmp/huangyu/
      --no_of_aln_threads 8
      -z pdc --dbname pmdb --schema sunset
      -u sunset_r -p yfishLabSunset
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - Alignment_isq_787_811_vs_633.xml

DAG_InspectAlignment:
  stage: test_run
  script:
    - echo "Output a InspectAlignmentPipeline DAG ... "
    - pwd
    #InspectAlignmentPipeline needs some compiled binaries
    - make all
    - ./ngs/qc/InspectAlignmentPipeline.py -a 633 -i 2112-2132 -l condor -z pdc
      --dbname pmdb --schema sunset -u sunset_r -p yfishLabSunset
      --home_path /y/home/huangyu --pymodulePath `pwd`
      --tmpDir /y/scratch/tmp/huangyu/
      -o InspectAln_2112_2132.xml
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - InspectAln_2112_2132.xml

DAG_InspectBaseQuality:
  stage: test_run
  script:
    - echo "Output a InspectBaseQualityPipeline DAG ... "
    - pwd
    - ./ngs/qc/InspectBaseQualityPipeline.py -a 633 -i 650-850 -l condor -z pdc
      --dbname pmdb --schema sunset -u sunset_r -p yfishLabSunset
      --home_path /y/home/huangyu --pymodulePath `pwd`
      --tmpDir /y/scratch/tmp/huangyu/
      -o InspectBaseQuality_650_850.xml
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - InspectBaseQuality_650_850.xml

InspectBaseQuality:
  stage: test_run
  script:
    - echo "Run a InspectBaseQuality.py ... "
    - pwd
    - mkdir input
    - ln -s individual_sequence/660_indID570_codeEC008_sequencer10000_seqType5_tissueID62_filtered0_batch1_version1/38130_660_WGC090564D_combined_R1_1_12.fastq.gz
      ./input
    - ./ngs/qc/InspectBaseQuality.py --drivername postgresql --hostname pdc
      --schema sunset --dbname pmdb
      --db_user sunset_r -p yfishLabSunset
      -i input/38130_660_WGC090564D_combined_R1_1_12.fastq.gz
      --logFilename input/38130_660_WGC090564D_combined_R1_1_12.log
      --read_sampling_rate 0.005 --quality_score_format Standard
    - rm input/38130_660_WGC090564D_combined_R1_1_12.fastq.gz
    - mv input output
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - output

uninstall:
  stage: uninstall
  script:
    - pip3 uninstall -y palos