before_script:
  - echo "before script"
  # let users can modify its own files. git object files are 444 (read-only for everyone.)
  - chmod u+w -R .git/

after_script:
  - echo "after script"

stages:
  - install
  - test
  - uninstall

install:
  stage: install
  script:
    - pip3 install --user ./


test_version:
  stage: test
  script:
    - echo "Checking the installed version"
    - python3 -c "import palos; print(palos.version)"

test_SunsetDB:
  stage: test
  script:
    - echo "Testing if SunsetDB.py can be run ... "
    - pwd
    - ./palos/db/SunsetDB.py -h

test_ImportSeq:
  stage: test
  script:
    - echo "Testing if ImportIndividualSequence2DB.py can be run ... "
    - pwd
    - ./db/import/ImportIndividualSequence2DB.py -h

uninstall:
  stage: uninstall
  script:
    - pip3 uninstall -y palos