
CXXTARGETS	= AbstractMatrixFileWalkerCC
CXXLDFLAGS 	= $(BoostLib)
CTARGETS	= 
SharedLibTargets	= AbstractMatrixFileWalkerCC.so

SRCS	= AbstractMatrixFileWalkerCC.cc

include ../Makefile.common
#overwrite Makefile.common
IncludeDirs	= -I`readlink -f ..`
