#!/bin/bash

set -e

TOPDIR=`pwd`
if test $# -lt 2 ; then
	echo ""
	echo "Usage:  $0 shellCommandFile shellOutputFile"
	echo ""
	echo "Note:"
	echo "	#. This is a shell program that runs shell commands from shellCommandFile and redirect the stdout to shellOutputFile."
	echo ""
	echo ""
	echo "Examples:"
	echo "  #run the ms_command.sh (contains a commandline to run simulation program, ms, generated by programs like history2ms.pl from PSMC)"
	echo "	$0 ms_command.sh msOutput.txt"
	exit 1
fi

shellCommandFile=$1
shellOutputFile=$2

sh $shellCommandFile > $shellOutputFile