from AbstractWorkflow import AbstractWorkflow
from AbstractNGSWorkflow import AbstractNGSWorkflow
from AbstractVCFWorkflow import AbstractVCFWorkflow
from AbstractAlignmentWorkflow import AbstractAlignmentWorkflow
from AbstractAlignmentAndVCFWorkflow import AbstractAlignmentAndVCFWorkflow
